// Samples/Angular/src/app/MinApp.ts
import { Component, OnInit } from '@angular/core';
import * as MindFusion from 'diagram-library';

import Diagram = MindFusion.Diagramming.Diagram;

@Component({
  selector: 'min-app',
  template: `<div className="App">
  <div class="header">
    Behavior
    <select id="behavior" (change)="onBehaviorChange($event)">
      <option value="3">LinkShapes</option>
      <option value="4">LinkTables</option>
      <option value="11">LinkContainers</option>
      <option value="26">LinkFreeShapes</option>
      <option value="0">Modify</option>
    </select>

    <span>{{"Nodes count: " + nodes}}</span>
    <span>{{"Links count: " + links}}</span>
  </div>

  <div class="container">
    <div class="main">
        <diagram-view 
        [diagram]="diagram" 
        [allowInplaceEdit]="true" 
        [routeLinks]="true" 
        [showGrid]="true"
        [linkHeadShapeSize] = "5"
        [backBrush]="'lightcyan'"
        (onNodeCreated)="onDiagramNodeCreated($event)"
        (onNodeDeleted)="onNodeDeleted($event)"
        (onLinkCreated)="onLinkCreated($event)"
        (onLinkDeleted)="onLinkDeleted($event)">
        </diagram-view>
    </div>
    <div class="sidebar">
      <h1>About this sample</h1>
      <p>A sample page that shows the basic functionality of Angular DiagramView.</p>
    </div>
  </div>

  <div class="footer">
    <p>Copyright 2020 MindFusion LLC.</p>
  </div>

</div>`
})
export class MinApp implements OnInit{
    

  diagram: Diagram;
  nodes: number;
  links: number;

  ngOnInit(): void{

    this.diagram = new Diagram();
    this.diagram.setShadowsStyle(MindFusion.Diagramming.ShadowsStyle.None);

    var shapeNode = this.diagram.getFactory().createShapeNode(20, 10, 50, 50);
    var tableNode = this.diagram.getFactory().createTableNode(100, 10, 50, 50);
    this.diagram.getFactory().createDiagramLink(shapeNode, tableNode);

    this.nodes = this.diagram.getNodes().length;
    this.links = this.diagram.getLinks().length;

  }

  onLinkCreated(event){
    this.links = this.diagram.getLinks().length;
  }
  onLinkDeleted(event){
    this.links = this.diagram.getLinks().length;
  }

  onDiagramNodeCreated(event) {
    var node = event.args.getNode();
    if (node instanceof MindFusion.Diagramming.TableNode) {
      node.setText("Table");
    }else if (node instanceof MindFusion.Diagramming.ContainerNode) {
      node.setText("Container");
      node.setFoldable(true);
    }
    this.nodes = this.diagram.getNodes().length;
  }
  onNodeDeleted(event){
    this.nodes = this.diagram.getNodes().length;
  }

  onBehaviorChange(e) {
    this.diagram.setBehavior(+e.target.value);
  }
}

// Samples/React/src/MinApp.js
import React, { Component } from 'react';
import Info from './Info';
import mf from 'diagram-library';
import { DiagramView } from 'diagram-library-react';

class MinApp extends Component {
  constructor(props) {
    super(props);

    // create the diagram
    var diagram = new mf.Diagramming.Diagram();
    diagram.setShadowsStyle(mf.Diagramming.ShadowsStyle.None);

    var shapeNode = diagram.getFactory().createShapeNode(20, 10, 50, 50);
    var tableNode = diagram.getFactory().createTableNode(100, 10, 50, 50);
    diagram.getFactory().createDiagramLink(shapeNode, tableNode);

    // set the model diagram in state
    this.state = {
      diagram: diagram,
      nodes: 2,
      links: 1,
      behavior: mf.Diagramming.Behavior.LinkShapes
    };
  }

  onDiagramChanged(sender, args) {
    this.setState({
      nodes: this.state.diagram.nodes.length,
      links: this.state.diagram.links.length,
    })
  }

  onDiagramNodeCreated(sender, args) {
    var node = args.getNode();
    if (node instanceof mf.Diagramming.TableNode) {
      node.setText("Table");
    }
    else if (node instanceof mf.Diagramming.ContainerNode) {
      node.setText("Container");
      node.setFoldable(true);
    }
  }

  onBehaviorChange(e) {
    this.setState({ behavior: +e.target.value });
  }

  render() {
    var props = {
      "allowInplaceEdit": true,
      "routeLinks": true,
      "showGrid": true,
      "backBrush": "lightcyan",
      "behavior": this.state.behavior
    };

    return (
      <div className="App">
        <div className="header">
          Behavior
          <select id="behavior" onChange={this.onBehaviorChange.bind(this)}>
            <option value="3">LinkShapes</option>
            <option value="4">LinkTables</option>
            <option value="11">LinkContainers</option>
            <option value="26">LinkFreeShapes</option>
            <option value="0">Modify</option>
          </select>

          <span>{"Nodes count: " + this.state.nodes}</span>
          <span>{"Links count: " + this.state.links}</span>
        </div>

        <div className="container">
          <div className="main">
            <DiagramView diagram={this.state.diagram} {...props}
              onDiagramChanged={(sender, args) => this.onDiagramChanged(sender, args)}
              onNodeCreated={(sender, args) => this.onDiagramNodeCreated(sender, args)} />
          </div>
          <div className="sidebar">
            <h1>About this sample</h1>
            <p>A sample page that shows the basic functionality of React DiagramView.</p>
            <Info />
          </div>
        </div>

        <div className="footer">
          <p>Copyright 2020 MindFusion LLC.</p>
        </div>

      </div>
    );
  }
}


export default MinApp;
