// Samples/React/src/Info.js
import React from 'react';

function Info() {
  return <div>
    <h1>About React Diagram</h1>
    <p>
      The DiagramView component is a React wrapper component for a diagram library that enables you to build any type of graph,
      flowchart, tree, org chart, diagram, process chart, database schema and much more.
      Includes a huge variety of predefined node and link shapes, automatic layout algorithms, many import and export options.
    </p>
    <h2>Features</h2>
    <ul>
      <li>Interactive zooming, scrolling, and panning</li>
      <li>Hundreds of built-in shapes and the ability to define custom shapes</li>
      <li>Table nodes with collapsible rows and spanning cells</li>
      <li>Many ready-to-use layouts, including tree, layered, fractal, and more</li>
      <li>Automatic link routing</li>
      <li>Lane grid</li>
      <li>Hierarchical grouping of diagram elements</li>
      <li>Undo and redo support</li>
      <li>Styles and themes</li>
      <li>Node effects</li>
      <li>Overview, NodeListView, ZoomControl, Ruler controls</li>
    </ul>
  </div>
}
export default Info;

// Samples/Vue/src/components/Info.vue


<template>
  <div>
    <h1>About Vue Diagram</h1>
    <p>
      The DiagramView component is a Vue wrapper component for a diagram library that enables you to build any type of graph,
      flowchart, tree, org chart, diagram, process chart, database schema and much more.
      Includes a huge variety of predefined node and link shapes, automatic layout algorithms, many import and export options.
    </p>
    <h2>Features</h2>
    <ul>
      <li>Interactive zooming, scrolling, and panning</li>
      <li>Hundreds of built-in shapes and the ability to define custom shapes</li>
      <li>Table nodes with collapsible rows and spanning cells</li>
      <li>Many ready-to-use layouts, including tree, layered, fractal, and more</li>
      <li>Automatic link routing</li>
      <li>Lane grid</li>
      <li>Hierarchical grouping of diagram elements</li>
      <li>Undo and redo support</li>
      <li>Styles and themes</li>
      <li>Node effects</li>
      <li>Overview, NodeListView, ZoomControl, Ruler controls</li>
    </ul>
  </div>
</template>

export default {
  name: "Info"
}
